### PR TITLE
Responsive

### PR DESCRIPTION
**Pull request by goyal-Dushi**
Made the header, footer, and projects section responsive :smile:

### CODE REVIEW

**Comment by Bryson69** [comment]
@goyal-Dushi Do you mind sharing a screenshot?

**Comment by vinzvinci** [comment]
Or enable the GitHub pages on your forked repository, and show the link here. 

Next time, please do comment on issue or create an issue first if there's no open issue related to your work ideas. It's a good practice to work with the issue first before making a PR.

**Comment by goyal-Dushi** [comment]
[https://drive.google.com/file/d/1Gyh226MuhCbsXNgRPyfijdlwK5NxBTZ1/view?usp=sharing](url)

Hey @Bryson69, here is the screen recording of the responsive design.

> @goyal-Dushi Do you mind sharing a screenshot?

**Comment by goyal-Dushi** [comment]
> @goyal-Dushi Do you mind sharing a screenshot?

Hey @Bryson69, below is the link for the responsive site.

[https://user-images.githubusercontent.com/40212568/117005022-658ac600-ad04-11eb-83a3-752b4ae73f33.mp4](url)

**Comment by goyal-Dushi** [comment]
> @goyal-Dushi Do you mind sharing a screenshot?

https://user-images.githubusercontent.com/40212568/117005762-42ace180-ad05-11eb-8c65-6580101234c5.mp4

Hey @Bryson69, here is the screen recording for the responsive site.

**Comment by goyal-Dushi** [comment]
> Or enable the GitHub pages on your forked repository, and show the link here.
> 
> Next time, please do comment on the issue or create an issue first if there's no open issue related to your work ideas. It's a good practice to work with the issue first before making a PR.

Ok @vinzvinci, I will remember that. Thank you.

**Comment by Bryson69** [comment]
This looks great. More than What I expected actually. Great work @goyal-Dushi. 
The Admin will have a look at it and decide. Otherwise, I think It's an awesome job.

**Review by vinzvinci — APPROVED** [review]
LGTM :+1: :100:

**Comment by goyal-Dushi** [comment]
> This looks great. More than What I expected actually. Great work @goyal-Dushi.
> The Admin will have a look at it and decide. Otherwise, I think It's an awesome job.

Thanks, @Bryson69, happy to contribute. :smile:

**Pull request merged**
