### PR TITLE
Support Our Program section added

### PR DESCRIPTION
**Pull request by amitroy-thedev**
## Related Issue 

- Information about the related issue 

Closes: # 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |
 
## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Review by vinzvinci — APPROVED** [review]
LGTM!

**Review by Tiansing — APPROVED** [review]
LGTM! this pr will be approved and labeled as hacktoberfest-accepted. Thank you!

**Comment by amitroy-thedev** [comment]
Thank you !!

**Comment by amitroy-thedev** [comment]
Hey @vinzvinci please label this project as hacktoberfest.. It didn't counted as a contribution in my hacktoberfest contest..

**Pull request merged**
