### PR TITLE
Create pull_request_template.md

### LINKED ISSUE #51: docs: add PR template

### PR DESCRIPTION
**Pull request by deephunt3r**
closes #51

### CODE REVIEW

**Comment by deephunt3r** [comment]
Let me know if you want any changes! Love to help the community

**Review by vinzvinci — CHANGES_REQUESTED** [review]
You put the file inside the ISSUE_TEMPLATE, please put it outside.

**Ex.**
.github/pull_request_template.md

**Comment by deephunt3r** [comment]
> You put the file inside the ISSUE_TEMPLATE, please put it outside.
> 
> **Ex.**
> .github/pull_request_template.md

sorry!

**Review by vinzvinci — APPROVED** [review]
Thank you. LGTM 👍

**Pull request merged**
